# Site settings
title: Gustavo Barrientos
email: gustavo.barrientos@acidstudios.me
description: > # this means to ignore newlines until "baseurl:"
  ¡Hola! Me llamo Gustavo Barrientos, soy Desarrollador de Software
  y escribo sobre Ingeniería de Software, Hardware etc..
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tavobarrientos
github_username:  tavobarrientos

# Build settings
markdown: kramdown
